name: CI Roslin Adama API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: roslin-adama-api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
              
      - name: Build with Maven
        run: mvn clean install

      - name: Report build results
        uses: gmazzo/publish-report-annotations@v1
        if: ${{ !cancelled() }}
        with:
          reports: | 
            roslin-adama-api/target/*.xml
             roslin-adama-api/target/surefire-reports/*.xml

