name: CI Roslin Adama API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: roslin-adama-api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
              
      - name: Build with Maven
        run: mvn clean install
    
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'roslin-adama-api/target/checkstyle-result.xml'

      - name: Publish Checkstyle report
        uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() || success() }}
        with:
          reports: |
            roslin-adama-api/target/*.xml
