name: Security Roslin Adama API

on:
  # Schedule to run every Monday at midnight UTC
  schedule:
    - cron: '0 0 * * 1'
  
  # Allows manual triggering from the GitHub Actions UI
  workflow_dispatch:

permissions:
  contents: write
  security-events: write    

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: roslin-adama-api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
              
      - name: Red Hat Dependency Analytics Scan
        uses: RHEcosystemAppEng/rhda-github-action@main
        with:
          manifest_directory: roslin-adama-api

